name: 'Update Manifests Rollouts'
description: 'Update appVersion and image tag for multiple repositories'

inputs:
  repos_and_folders:
    description: 'Map of repositories, folders, and secrets'
    required: true
  image_tag:
    description: 'New image tag'
    required: true

runs:
  using: 'node20'
  main: 'index.js'
