name: 'Update Repository Manifests'
description: 'Update image tag and appVersion for a single repository'

inputs:
  repo:
    description: 'Repository name (owner/repo)'
    required: true
  folder:
    description: 'Folder containing the Helm chart'
    required: true
  secret:
    description: 'GitHub token for accessing the repository'
    required: true
  image_tag:
    description: 'New image tag to be used in the Helm charts'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout Manifests
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.repo }}
        token: ${{ inputs.secret }}
        ref: main

    - name: Set up Git
      run: |
        git config --global user.name "GitHub-Actions-CI-Build"
        git config --global user.email "user@gitHubActions.com"
      shell: bash  # Specify the shell explicitly

    - name: Update Helm Values
      run: |
        sed -i "s/tag: .*/tag: ${{ inputs.image_tag }}/" ${{ inputs.folder }}/values.yaml
      shell: bash  # Specify the shell explicitly

    - name: Increment appVersion
      id: increment_version
      run: |
        increment_version() {
          local chart_path=$1
          local env_var_name=$2
        
          current_version=$(grep '^appVersion:' ${chart_path}/Chart.yaml | cut -d ' ' -f 2 | tr -d '"')
          current_date=$(date +'%Y.%m')
        
          if [[ $current_version == $current_date* ]]; then
            patch_number=$(echo $current_version | cut -d '.' -f 3)
            patch_number=$((patch_number + 1))
          else
            patch_number=0
          fi
        
          new_version="${current_date}.${patch_number}"
          echo "${env_var_name}=${new_version}" >> $GITHUB_ENV
        }
        
        increment_version ${{ inputs.folder }} "new_version"
      shell: bash  # Specify the shell explicitly

    - name: Update appVersion in Chart.yaml
      run: |
        sed -i "s/^appVersion:.*/appVersion: \"${{ env.new_version }}\"/" ${{ inputs.folder }}/Chart.yaml
      shell: bash  # Specify the shell explicitly

    - name: Check for Changes and Commit
      env:
        IMAGE_TAG: ${{ inputs.image_tag }}  # Pass the image tag input as an environment variable
      run: |
        git add .
        if ! git diff-index --quiet HEAD --; then
          if [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
            git commit -m "Updated image tag to ${IMAGE_TAG} and incremented app versions"
            git push origin main || echo "Push failed, possibly due to lack of permissions"
          else
            # Create a pull request if the branch is not main
            TIMESTAMP=$(date +'%Y%m%d%H%M%S')
            BRANCH_NAME="update-feature/main-${TIMESTAMP}"
            git checkout -b $BRANCH_NAME
            git commit -m "Update image tag to ${IMAGE_TAG} and incremented app versions"
            git push -u origin $BRANCH_NAME
        
            # Create the pull request using GitHub CLI
            gh pr create --title "Updated image tag to ${IMAGE_TAG}" --body "This PR updates the image tag to ${IMAGE_TAG}."
          fi
        else
          echo "No changes detected."
        fi
      shell: bash

    - name: Checkout Original Repository
      uses: actions/checkout@v4
      with:
        repository: ${{ github.repository }}