name: Backend CI Pipeline

# Workflow triggers for pull requests, manual dispatch, and pushes to specific branches.
on:
  pull_request:
    types: [assigned]
    branches: [main]
  workflow_dispatch:
  push:
    branches:
      - main
      - dev/**

jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    environment: backend-test-dev
    outputs:
      image_tag: ${{ steps.build.outputs.image_tag }}
    steps:
      # Checkout the repository code again for Docker build.
      - name: Checkout Code
        uses: actions/checkout@v4

      # Build and push Docker images with tags based on branch name and timestamp.
      - name: Build and Push Docker Image
        id: build
        run: |
          export TZ=Asia/Kolkata
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr '/' '-')
          IMAGE_TAG="${{ secrets.DOCKER_USERNAME }}/github-actions-backend:${BRANCH_NAME}-${TIMESTAMP}"
          # Output the constructed image tag to the GitHub Actions output variable.
          echo "image_tag=${BRANCH_NAME}-${TIMESTAMP}" >> $GITHUB_OUTPUT

  update-manifests-rollouts:
    needs: docker-build-push
    runs-on: ubuntu-latest
    environment: backend-test-dev
    steps:
      # Checkout the repository code again for Docker build.
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Update repo 1 (rollouts-with-argo-cd)
        uses: ./.github/actions/update-repo
        with:
          repo: "yadnesh082024/rollouts-with-argo-cd"
          folder: "spring-boot-helm-chart-argo-rollout"
          secret: ${{ secrets.GH_TOKEN_ROLLOUTS_REPO }}
          image_tag: ${{ needs.docker-build-push.outputs.image_tag }}

